"""
Per-fighter volume projections: significant strikes landed, takedowns landed.

WHY THESE MARKETS. Polymarket does not price strike or takedown props, so the
site has never shown them -- but DraftKings and FanDuel both do, per fighter,
and a reader who bets there has no model number to compare against. This is
the one place where having no book line is an argument FOR building rather
than against: the projection is the only number available.

THE STRUCTURAL POINT, and the reason this is worth doing at all. ESPN gives
per-fight TOTALS, and a total conflates pace with fight length -- a finisher's
strike count is suppressed by the very trait that makes him dangerous. Reading
career averages off a stats page inherits that confound. Separating them does
not:

    E[strikes] = strikes-per-MINUTE  x  E[fight minutes]

The rate comes from the backfill (landed / minutes actually fought). The
duration comes from the method model's finish-vs-decision split and the round
distribution already used for round props. Both sides are things this project
already computes and has reason to trust; the projection is their product,
not a new model.

DELIBERATELY THE SIMPLE VERSION. A fighter's output also depends on WHO he is
facing -- volume drops against a good defensive opponent, and
sig_strikes_absorbed_per_min is now available to express that. That blend is
more correct in principle and is the obvious next step, but it adds a
parameter with no baseline to beat. This version exists to BE that baseline:
if the opponent adjustment cannot beat own-rate-only on a point-in-time
backtest, it is not earning its place, and there would be no way to know that
without measuring it against something.

RANGES, NOT POINT ESTIMATES. "87 significant strikes" is false precision for a
quantity whose single largest driver is how long the fight lasts. The range
here is generated by conditioning on each possible finish round and taking the
spread across that distribution -- so it widens for a fight that might end in
round one and narrows for two durable decision fighters, which is exactly the
information a bettor needs when the line is 82.5.
"""

# A round is five minutes. Fights that end mid-round are handled by the
# midpoint convention below, not by pretending rounds are indivisible.
ROUND_MINUTES = 5.0

# Where in a round a finish lands, on average. Midpoint is the honest default:
# finishes are mildly front-loaded WITHIN a round, but not enough to justify a
# fitted constant on top of an already-estimated round distribution.
FINISH_POINT_IN_ROUND = 0.5

# Below this the rate is too noisy to project from -- same reasoning as the
# backfill's own floor, restated here because a caller may hand us a row that
# came from somewhere else.
MIN_MINUTES_FOR_PROJECTION = 25.0


def expected_fight_minutes(finish_prob: float, round_shares: list[float],
                           scheduled_rounds: int = 3) -> float:
    """
    Expected fight length in minutes.

    Decisions run the full distance. Finishes land at the midpoint of whatever
    round they occur in, weighted by the same per-round share table the round
    props already use -- so this cannot disagree with the Over/Under grid
    shown elsewhere on the same fight.
    """
    full = scheduled_rounds * ROUND_MINUTES
    if not round_shares:
        return full
    total_share = sum(round_shares) or 1.0
    finish_minutes = sum(
        (share / total_share) * ((i + FINISH_POINT_IN_ROUND) * ROUND_MINUTES)
        for i, share in enumerate(round_shares)
    )
    finish_prob = max(0.0, min(1.0, float(finish_prob)))
    return finish_prob * finish_minutes + (1 - finish_prob) * full


def _minutes_by_finish_round(round_shares: list[float], scheduled_rounds: int) -> list[tuple]:
    """[(probability, minutes)] over every way the fight can end."""
    full = scheduled_rounds * ROUND_MINUTES
    total = sum(round_shares) or 1.0
    out = [(share / total, (i + FINISH_POINT_IN_ROUND) * ROUND_MINUTES)
           for i, share in enumerate(round_shares) if share > 0]
    out.append((1.0, full))          # the decision branch, weighted by caller
    return out


def project_volume(rate_per_min: float | None, finish_prob: float,
                   round_shares: list[float], scheduled_rounds: int = 3,
                   per_15: bool = False) -> dict | None:
    """
    {'expected', 'low', 'high', 'minutes'} or None when the rate is unusable.

    `per_15` for takedown rates, which are conventionally quoted per 15
    minutes rather than per minute.
    """
    if rate_per_min is None:
        return None
    try:
        rate = float(rate_per_min)
    except (TypeError, ValueError):
        return None
    if rate != rate or rate < 0:
        return None
    if per_15:
        rate = rate / 15.0

    minutes = expected_fight_minutes(finish_prob, round_shares, scheduled_rounds)
    expected = rate * minutes

    # Range from DURATION uncertainty, which dominates. Each branch is a
    # different fight length; the spread across them is the honest interval,
    # and it narrows automatically for two fighters who always go the
    # distance.
    branches = []
    fp = max(0.0, min(1.0, float(finish_prob)))
    total = sum(round_shares) or 1.0
    for i, share in enumerate(round_shares):
        if share <= 0:
            continue
        branches.append((fp * share / total, (i + FINISH_POINT_IN_ROUND) * ROUND_MINUTES))
    branches.append((1 - fp, scheduled_rounds * ROUND_MINUTES))

    branches.sort(key=lambda b: b[1])
    lo = hi = None
    cum = 0.0
    for prob, mins in branches:
        cum += prob
        if lo is None and cum >= 0.20:
            lo = rate * mins
        if hi is None and cum >= 0.80:
            hi = rate * mins
    if lo is None:
        lo = expected
    if hi is None:
        hi = rate * branches[-1][1]

    return {
        "expected": round(expected, 1),
        "low": round(min(lo, expected), 1),
        "high": round(max(hi, expected), 1),
        "minutes": round(minutes, 1),
    }


def build_volume_projections(row_a: dict, row_b: dict, name_a: str, name_b: str,
                             finish_prob: float, round_shares: list[float],
                             scheduled_rounds: int = 3) -> list[dict]:
    """
    Rows for the projection table: two fighters x two markets.

    Returns [] when neither fighter has enough timed action, so the section
    can be omitted entirely rather than rendered empty -- an empty table
    invites the reader to wonder what broke.
    """
    out = []
    for row, name in ((row_a, name_a), (row_b, name_b)):
        minutes = row.get("fight_minutes_total")
        try:
            enough = minutes is not None and float(minutes) >= MIN_MINUTES_FOR_PROJECTION
        except (TypeError, ValueError):
            enough = False
        if not enough:
            continue
        for col, label, per15 in (
            ("sig_strikes_landed_per_min", "Significant strikes landed", False),
            ("td_landed_per_15", "Takedowns landed", True),
        ):
            proj = project_volume(row.get(col), finish_prob, round_shares,
                                  scheduled_rounds, per_15=per15)
            if proj is None:
                continue
            out.append({
                "fighter": name,
                "market": label,
                "expected": proj["expected"],
                "low": proj["low"],
                "high": proj["high"],
                "minutes": proj["minutes"],
            })
    return out
